INPUT:
    # we use image net pretrained model, which is not based on bgr255. BGR255
    # is used for caffe2 model as in defaults.py
    TO_BGR255: false
    PIXEL_MEAN: [0.485, 0.456, 0.406]
    PIXEL_STD: [0.229, 0.224, 0.225]
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: output/imagenet2012_e2e_faster_rcnn_R_34_FPN_fast_CM_basemodel_BS2048_MaxIter120e_LR0.8_single_StepLR30e_Freeze0_RGB/snapshot/model_iter_0075068.pt
  BACKBONE:
    CONV_BODY: "R-34-FPN-Fast"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 128
    BATCHNORM_EPS: 1e-5
  RPN:
    RPN_HEAD: "SimpleRPNHead"
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32)
    ANCHOR_SIZES: (16, 32, 64, 128)
    ASPECT_RATIOS: (1.5,)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    NMS_THRESH: 0.5
    BG_IOU_THRESHOLD: 0.4
    FG_IOU_THRESHOLD: 0.5
  ROI_HEADS:
    USE_FPN: True
    DETECTIONS_PER_IMG: 1000
    SCORE_THRESH: 0.01
  ROI_BOX_HEAD:
    NUM_CLASSES: 2
    POOLER_RESOLUTION: 4
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
DATASETS:
  TRAIN: ("datasets/coco/yaml/train.v0.yaml",)
  TEST: ("coco_2017_val",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  IMS_PER_BATCH: 16
  CHECKPOINT_PERIOD: 10000
OUTPUT_DIR: "output/"

